import Head from 'next/head'
import { emotionStyles } from '../styles/index.ts'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={emotionStyles.main}>
        <h1 className={emotionStyles.h1}>
          Welcome to gridレイアウト!
        </h1>

        <div className={emotionStyles.container}>
          <div className={emotionStyles.div}>box</div>
          <div className={emotionStyles.div}>box</div>
          <div className={emotionStyles.div}>box</div>
          <div className={emotionStyles.div}>box</div>
          <div className={emotionStyles.div}>box</div>
          <div className={emotionStyles.div}>box</div>
          <div className={emotionStyles.div}>box</div>
          <div className={emotionStyles.div}>box</div>
          <div className={emotionStyles.div}>box</div>
          <div className={emotionStyles.div}>box</div>
          <div className={emotionStyles.div}>box</div>
          <div className={emotionStyles.div}>box</div>
          <div className={emotionStyles.div}>box</div>
          <div className={emotionStyles.div}>box</div>
          <div className={emotionStyles.div}>box</div>
          <div className={emotionStyles.div}>box</div>
          <div className={emotionStyles.div}>box</div>
          <div className={emotionStyles.div}>box</div>
          <div className={emotionStyles.div}>box</div>
          <div className={emotionStyles.div}>box</div>
          <div className={emotionStyles.div}>box</div>
        </div>
      </main>
    </div>
  )
}
